export const currentUser = {
  id: 'u13',
  name: 'Alex Rivera',
  handle: '@alexriv',
  avatar: '/api/uploads?path=images/orra-logo.png',
  level: 42,
  auraTokens: 12580,
  bio: 'Creating vibes | Dance enthusiast | Tech lover | Building the future one post at a time',
  followers: 12800,
  following: 845,
  posts: 342,
  coverImage: '/api/uploads?path=images/profile-cover.png',
  location: '',
  website: 'orra.app/alexriv',
  joinDate: 'March 2025',
  badges: ['Early Adopter', 'Dance Champion', 'Top Creator'],
};

export const users = [
  { id: 'u1', name: 'Jessica Art', handle: '@jessart', avatar: '/images/avatars/bots/bot01.jpg', online: true, verified: true },
  { id: 'u2', name: 'David Chen', handle: '@davchen', avatar: '/images/avatars/bots/bot02.jpg', online: true, verified: false },
  { id: 'u3', name: 'Sarah Kim', handle: '@sarahkim', avatar: '/images/avatars/bots/bot03.jpg', online: false, verified: false },
  { id: 'u4', name: 'Marcus Rivera', handle: '@marcusr', avatar: '/images/avatars/bots/bot04.jpg', online: true, verified: true },
  { id: 'u5', name: 'Elena Rodriguez', handle: '@elenarod', avatar: '/images/avatars/bots/bot05.jpg', online: false, verified: false },
  { id: 'u6', name: 'Tech Daily', handle: '@techdaily', avatar: '/images/avatars/bots/bot06.jpg', online: false, verified: true },
  { id: 'u7', name: 'Wellness Guru', handle: '@wellnessg', avatar: '/images/avatars/bots/bot07.jpg', online: true, verified: true },
  { id: 'u8', name: 'Cyber Drifter', handle: '@cyberdrift', avatar: '/images/avatars/bots/bot08.jpg', online: false, verified: false },
  { id: 'u9', name: 'Music Central', handle: '@musiccentral', avatar: '/images/avatars/bots/bot09.jpg', online: true, verified: true },
  { id: 'u10', name: 'Luna Sky', handle: '@lunasky', avatar: '/images/avatars/bots/bot10.jpg', online: true, verified: true },
  { id: 'u11', name: 'Kai Storm', handle: '@kaistorm', avatar: '/images/avatars/bots/bot11.jpg', online: false, verified: false },
  { id: 'u12', name: 'Nova Blaze', handle: '@novablaze', avatar: '/images/avatars/bots/bot12.jpg', online: true, verified: false },
  { id: 'u14', name: 'Jay Parker', handle: '@jayparker', avatar: '/images/avatars/bots/bot14.jpg', online: true, verified: false },
  { id: 'u15', name: 'Maya Chen', handle: '@mayachen', avatar: '/images/avatars/bots/bot15.jpg', online: false, verified: true },
  { id: 'u16', name: 'Dre Williams', handle: '@drewilliams', avatar: '/images/avatars/bots/bot16.jpg', online: true, verified: true },
];

export const stories = [
  { id: 's0', user: currentUser, isOwn: true, image: '/api/uploads?path=images/dance-party.png', viewed: false },
  { id: 's1', user: users[0], image: '/images/stories/story1.jpg', viewed: false },
  { id: 's2', user: users[1], image: '/images/stories/story2.jpg', viewed: false },
  { id: 's3', user: users[3], image: '/images/stories/story3.jpg', viewed: true },
  { id: 's4', user: users[4], image: '/images/stories/story4.jpg', viewed: false },
  { id: 's5', user: users[6], image: '/images/stories/story5.jpg', viewed: true },
  { id: 's6', user: users[8], image: '/images/stories/story6.jpg', viewed: false },
  { id: 's7', user: users[9], image: '/images/stories/story7.jpg', viewed: false },
  { id: 's8', user: users[11], image: '/images/stories/story8.jpg', viewed: true },
  // 8 new stories
  { id: 's9', user: users[12], image: '/images/stories/story9.jpg', viewed: false },
  { id: 's10', user: users[13], image: '/images/stories/story10.jpg', viewed: false },
  { id: 's11', user: users[14], image: '/images/stories/story11.jpg', viewed: true },
  { id: 's12', user: users[2], image: '/images/stories/story12.jpg', viewed: false },
  { id: 's13', user: users[5], image: '/images/stories/story13.jpg', viewed: false },
  { id: 's14', user: users[7], image: '/images/stories/story14.jpg', viewed: true },
  { id: 's15', user: users[10], image: '/images/stories/story15.jpg', viewed: false },
  { id: 's16', user: currentUser, image: '/images/stories/story16.jpg', viewed: false },
];

// vibeTag maps posts to Vibe Check moods: hyped, laughing, chill, dramatic, focused, peaceful
export const feedPosts = [
  {
    id: 'p1',
    user: users[0],
    text: 'Just finished my latest digital art piece! The neon aesthetic is everything — spent 12 hours on this one and every minute was worth it. What do you think?',
    images: ['/images/posts/art1.jpg'],
    likes: 2341,
    comments: 189,
    shares: 67,
    time: '2h',
    verified: true,
    type: 'image' as const,
    vibeTag: 'dramatic',
  },
  {
    id: 'p2',
    user: users[5],
    text: 'Breaking: AI achieves new milestone in creative generation. The future is here and it is mind-blowing. This changes everything we know about content creation and digital art.',
    images: [],
    likes: 8912,
    comments: 456,
    shares: 1234,
    time: '3h',
    verified: true,
    type: 'text' as const,
    vibeTag: 'focused',
  },
  {
    id: 'p3',
    user: users[3],
    text: 'Dance practice went hard today! New choreo dropping this weekend — you do not want to miss this one. Been working on something special for the ORRA Dance Off!',
    images: ['/images/posts/dance1.jpg', '/images/posts/dance2.jpg'],
    likes: 5678,
    comments: 234,
    shares: 156,
    time: '4h',
    verified: true,
    type: 'image' as const,
    vibeTag: 'hyped',
  },
  {
    id: 'p4',
    user: users[4],
    text: 'Sunset vibes from Barcelona! Travel changes your perspective on everything. Every corner of this city tells a story, and I am here for all of it.',
    images: ['/images/posts/barcelona-sunset.jpg'],
    likes: 3456,
    comments: 123,
    shares: 89,
    time: '5h',
    verified: false,
    type: 'image' as const,
    vibeTag: 'chill',
  },
  {
    id: 'p5',
    user: users[6],
    text: 'Morning routine tip: Start with 5 minutes of breathwork before checking your phone. Game changer for mental clarity. Your mind will thank you, trust me on this one.',
    images: [],
    likes: 1567,
    comments: 98,
    shares: 234,
    time: '6h',
    verified: true,
    type: 'text' as const,
    vibeTag: 'peaceful',
  },
  {
    id: 'p6',
    user: users[8],
    text: 'NEW TRACK ALERT! Just dropped "Neon Dreams" — this is the official track for the ORRA Dance Off 2027 challenge! Link in bio! Let us see those moves!',
    images: ['/images/posts/album1.jpg'],
    likes: 7890,
    comments: 567,
    shares: 890,
    time: '7h',
    verified: true,
    type: 'image' as const,
    vibeTag: 'hyped',
  },
  {
    id: 'p7',
    user: users[7],
    text: 'When your WiFi dies mid-game and you just stare at the screen like... RIP my killstreak. Anyone else been there? 😂😭',
    images: ['/images/posts/gaming-setup-leds.jpg', '/images/posts/gaming-setup-leds.jpg'],
    likes: 4523,
    comments: 345,
    shares: 567,
    time: '8h',
    verified: false,
    type: 'image' as const,
    vibeTag: 'laughing',
  },
  {
    id: 'p8',
    user: users[9],
    text: 'Just hit 1 million ORRA tokens! From zero to hero in 6 months. The secret? Consistency, authentic content, and always showing up for the community. Dream big, grind harder!',
    images: [],
    likes: 12340,
    comments: 890,
    shares: 2100,
    time: '10h',
    verified: true,
    type: 'text' as const,
    vibeTag: 'hyped',
  },
  {
    id: 'p9',
    user: users[1],
    text: 'Finally shipped my side project after 3 months of late nights! It is a real-time collaboration tool for digital artists. Nothing fancy, just something I wished existed. Open source link in my bio — would love your feedback!',
    images: ['/images/posts/laptop-code.jpg'],
    likes: 4210,
    comments: 312,
    shares: 578,
    time: '11h',
    verified: false,
    type: 'image' as const,
    vibeTag: 'focused',
  },
  {
    id: 'p10',
    user: users[2],
    text: 'Golden hour at the coast today was absolutely unreal. Sometimes you just have to put the phone down and soak it in... okay maybe take ONE photo first then soak it in. Nature really outdid herself with this one.',
    images: ['/images/posts/mountain.jpg', '/images/posts/barcelona-alley.jpg', '/images/posts/city-night.jpg'],
    likes: 6789,
    comments: 234,
    shares: 445,
    time: '12h',
    verified: false,
    type: 'image' as const,
    vibeTag: 'chill',
  },
  {
    id: 'p11',
    user: users[10],
    text: 'Landed the tre flip down the 8 stair today! Took about 50 tries and my ankles are screaming but we finally got the clip. Persistence pays off every single time. Full video dropping on Prism later tonight!',
    images: ['/images/posts/basketball.jpg'],
    likes: 3890,
    comments: 178,
    shares: 234,
    time: '13h',
    verified: false,
    type: 'image' as const,
    vibeTag: 'hyped',
  },
  {
    id: 'p12',
    user: users[11],
    text: 'Studio session went from 10 PM to 4 AM. Lost track of time completely. When the beat hits right you just keep going. New EP coming this summer — this is just a taste of what is cooking.',
    images: [],
    likes: 5670,
    comments: 345,
    shares: 678,
    time: '14h',
    verified: false,
    type: 'text' as const,
    vibeTag: 'dramatic',
  },
  {
    id: 'p13',
    user: users[0],
    text: 'POV: You spent 6 hours on a piece and your cat walks across the keyboard and somehow makes it better. Should I keep the accidental layer? Honest opinions please — I am genuinely torn on this one.',
    images: ['/images/posts/art-block-canvas.jpg'],
    likes: 8920,
    comments: 567,
    shares: 1230,
    time: '15h',
    verified: true,
    type: 'image' as const,
    vibeTag: 'laughing',
  },
  {
    id: 'p14',
    user: users[6],
    text: 'Deep stretch session followed by cold plunge. The contrast therapy is no joke — my recovery time has improved dramatically. If you have not tried it yet, start with 30 seconds in cold water and work your way up. Your body will adapt faster than you think.',
    images: [],
    likes: 2100,
    comments: 145,
    shares: 189,
    time: '16h',
    verified: true,
    type: 'text' as const,
    vibeTag: 'peaceful',
  },
  {
    id: 'p15',
    user: users[5],
    text: 'This new open-source LLM just dropped and it is competitive with models 10x its size. The open-source community is moving at insane speed. We are living in the most exciting era of technology. What a time to be building.',
    images: ['/images/posts/orra-dev-desk.jpg'],
    likes: 11200,
    comments: 789,
    shares: 2340,
    time: '17h',
    verified: true,
    type: 'image' as const,
    vibeTag: 'focused',
  },
  {
    id: 'p16',
    user: users[4],
    text: 'Made paella from scratch using my abuela secret recipe! The sofrito is the key — slow cook it for at least 40 minutes. Took me 3 attempts to get it right but this one is perfect. Swipe for the step-by-step!',
    images: ['/images/posts/butter-chicken.jpg', '/images/posts/brunch.jpg'],
    likes: 5430,
    comments: 398,
    shares: 312,
    time: '18h',
    verified: false,
    type: 'image' as const,
    vibeTag: 'chill',
  },
  {
    id: 'p17',
    user: users[3],
    text: 'That feeling when the beat drops and your body just MOVES. No thinking, no planning, pure instinct. Dance is the most honest form of expression. Channel everything into the movement.',
    images: [],
    likes: 7890,
    comments: 456,
    shares: 890,
    time: '19h',
    verified: true,
    type: 'text' as const,
    vibeTag: 'dramatic',
  },
  {
    id: 'p18',
    user: users[9],
    text: 'Cozy night in with candles, lo-fi beats, and my journal. Sometimes the most productive thing you can do is slow down and reflect. Grateful for the quiet moments between the chaos. Who else is in their soft era?',
    images: ['/images/posts/poem-coffee-cup.jpg'],
    likes: 3210,
    comments: 201,
    shares: 156,
    time: '20h',
    verified: true,
    type: 'image' as const,
    vibeTag: 'peaceful',
  },
  {
    id: 'p19',
    user: users[7],
    text: 'My screen time report says 14 hours yesterday and honestly I am not even mad. When you are deep in the cyberpunk zone, time becomes a suggestion. Currently building a neural network visualizer and it looks absolutely INSANE.',
    images: ['/images/posts/city-night.jpg', '/images/posts/gaming-setup-leds.jpg'],
    likes: 6780,
    comments: 423,
    shares: 789,
    time: '22h',
    verified: false,
    type: 'image' as const,
    vibeTag: 'focused',
  },
  {
    id: 'p20',
    user: users[8],
    text: 'Just got back from the most incredible live show! The energy in that room was UNREAL. 20,000 people singing every word. This is why live music matters — no recording can capture that feeling. My ears are still ringing and I am not complaining one bit.',
    images: ['/images/posts/open-mic.jpg'],
    likes: 9100,
    comments: 623,
    shares: 1100,
    time: '1d',
    verified: true,
    type: 'image' as const,
    vibeTag: 'hyped',
  },
  {
    id: 'p21',
    user: users[1],
    text: 'Me: I will just fix this one tiny bug. Also me 6 hours later: *has rewritten the entire authentication system* The rabbit hole is real people. At least the code is cleaner now... I think.',
    images: [],
    likes: 7650,
    comments: 534,
    shares: 1890,
    time: '1d',
    verified: false,
    type: 'text' as const,
    vibeTag: 'laughing',
  },
  {
    id: 'p22',
    user: users[2],
    text: 'Morning fog rolling through the mountains. Shot this on my phone — no filter needed when nature does the editing for you. Sometimes the best camera is the one you have in your pocket. Woke up at 5 AM for this and it was absolutely worth every lost minute of sleep.',
    images: ['/images/posts/mountain.jpg'],
    likes: 4560,
    comments: 178,
    shares: 345,
    time: '1d',
    verified: false,
    type: 'image' as const,
    vibeTag: 'chill',
  },
  {
    id: 'p23',
    user: users[10],
    text: 'New skatepark opened downtown and it is BEAUTIFUL. Perfect transitions, smooth concrete, and a killer bowl section. If you are in the city you gotta check it out. Already planning a session there this weekend. Who is down?',
    images: ['/images/posts/basketball.jpg', '/images/posts/coaching-field.jpg'],
    likes: 2890,
    comments: 167,
    shares: 234,
    time: '1d',
    verified: false,
    type: 'image' as const,
    vibeTag: 'hyped',
  },
  {
    id: 'p24',
    user: users[11],
    text: 'Spend 10 minutes today just listening — really listening — to a song you love. No phone, no scrolling, no multitasking. Just the music. You will hear things you never noticed before. Music deserves your full attention sometimes.',
    images: [],
    likes: 1890,
    comments: 123,
    shares: 167,
    time: '1d',
    verified: false,
    type: 'text' as const,
    vibeTag: 'peaceful',
  },
  {
    id: 'p25',
    user: users[0],
    text: 'Just got featured in the ORRA Digital Art Spotlight! This is honestly the best feeling ever. From posting my first sketch here to being recognized by the community — proof that sharing your journey matters. Thank you all for the love and support!',
    images: ['/images/posts/art1.jpg'],
    likes: 15600,
    comments: 920,
    shares: 3400,
    time: '2h',
    verified: true,
    type: 'image' as const,
    vibeTag: 'hyped',
  },
  {
    id: 'p26',
    user: users[3],
    text: 'Teaching my little cousin the basics of hip-hop and she already has better rhythm than half the people in my dance class. Kids are sponges — they just absorb everything. Future star in the making for real!',
    images: ['/images/posts/dance-student-nailing.jpg'],
    likes: 8920,
    comments: 567,
    shares: 1230,
    time: '3h',
    verified: true,
    type: 'image' as const,
    vibeTag: 'chill',
  },
  {
    id: 'p27',
    user: users[5],
    text: 'The quietest people have the loudest minds. Spent the morning deep-diving into quantum computing research and I am fairly convinced we are closer to a breakthrough than anyone realizes. The papers coming out of CERN right now are absolutely fascinating.',
    images: [],
    likes: 5430,
    comments: 345,
    shares: 678,
    time: '4h',
    verified: true,
    type: 'text' as const,
    vibeTag: 'focused',
  },
  {
    id: 'p28',
    user: users[9],
    text: 'OOTD but make it ethereal. Layered this vintage sheer top over a neon bodysuit and I am OBSESSED. Fashion is about taking risks and expressing who you really are inside. Never play it safe with your style!',
    images: ['/images/posts/met-gala-orra.jpg', '/images/posts/brunch.jpg'],
    likes: 11200,
    comments: 780,
    shares: 1560,
    time: '5h',
    verified: true,
    type: 'image' as const,
    vibeTag: 'dramatic',
  },
  {
    id: 'p29',
    user: users[7],
    text: 'My smart home just turned on the disco lights, started playing techno, and ordered pizza at 3 AM. I did not program any of this. Either I have a ghost or my AI assistant has entered its rebellious phase. Either way, the pizza was actually really good.',
    images: [],
    likes: 14200,
    comments: 890,
    shares: 3200,
    time: '6h',
    verified: false,
    type: 'text' as const,
    vibeTag: 'laughing',
  },
  {
    id: 'p30',
    user: users[4],
    text: 'There is something magical about cooking a meal from scratch while listening to jazz. No rush, no stress, just you and the ingredients transforming into something beautiful. Made a mushroom risotto that took two hours and it was absolutely worth every minute of stirring.',
    images: ['/images/posts/butter-chicken.jpg'],
    likes: 4560,
    comments: 234,
    shares: 312,
    time: '7h',
    verified: false,
    type: 'image' as const,
    vibeTag: 'peaceful',
  },
  {
    id: 'p31',
    user: users[6],
    text: 'Cold shower challenge: Day 30. Here is what I learned — the first 10 seconds never get easier but your mind gets stronger. It is not about the water temperature, it is about choosing discomfort on purpose. That discipline spills into every area of your life.',
    images: [],
    likes: 6780,
    comments: 456,
    shares: 890,
    time: '8h',
    verified: true,
    type: 'text' as const,
    vibeTag: 'focused',
  },
  {
    id: 'p32',
    user: users[8],
    text: 'SURPRISE DROP! Just released an acoustic version of "Neon Dreams" — stripped it all back to just piano and vocals. Sometimes the simplest version of a song hits the hardest. Let me know which version you prefer!',
    images: ['/images/posts/bedroom-studio-late.jpg'],
    likes: 9870,
    comments: 723,
    shares: 1450,
    time: '9h',
    verified: true,
    type: 'image' as const,
    vibeTag: 'chill',
  },
  {
    id: 'p33',
    user: users[2],
    text: 'Got up at 4:30 AM to catch the supermoon setting over the ocean. My hands were freezing, the tripod almost blew over twice, but I got THE shot. Sometimes the best photographs come from the most uncomfortable moments. Worth every second of lost sleep.',
    images: ['/images/posts/mountain.jpg', '/images/posts/city-night.jpg'],
    likes: 7650,
    comments: 432,
    shares: 890,
    time: '10h',
    verified: false,
    type: 'image' as const,
    vibeTag: 'dramatic',
  },
  {
    id: 'p34',
    user: users[10],
    text: 'Skate documentary filming starts next week! We are hitting 5 cities in 10 days and documenting the underground skate scene in each one. This has been a dream project for 3 years and it is finally happening. Stay tuned for behind the scenes content!',
    images: ['/images/posts/basketball.jpg'],
    likes: 5430,
    comments: 345,
    shares: 678,
    time: '12h',
    verified: false,
    type: 'image' as const,
    vibeTag: 'hyped',
  },
  {
    id: 'p35',
    user: users[1],
    text: 'Interview at a FAANG company tomorrow. Not nervous at all. Absolutely zero anxiety. Totally calm and collected. ...Okay who am I kidding I have reviewed my algorithms 47 times today. Send good vibes and maybe a miracle!',
    images: [],
    likes: 8900,
    comments: 678,
    shares: 1230,
    time: '14h',
    verified: false,
    type: 'text' as const,
    vibeTag: 'laughing',
  },
  {
    id: 'p36',
    user: users[11],
    text: 'Midnight studio session update: Just made the hardest beat of my life. Layered a reversed vocal sample over an 808 pattern that hits so different. The neighbors are probably going to complain but art requires sacrifice. This one is going on the EP for sure.',
    images: ['/images/posts/studio-beats.jpg', '/images/posts/bedroom-studio-late.jpg'],
    likes: 6780,
    comments: 456,
    shares: 890,
    time: '16h',
    verified: false,
    type: 'image' as const,
    vibeTag: 'hyped',
  },
];

// Comedy content for Vibe Check laughing mode
export const comedyPosts = [
  { id: 'cp1', user: users[7], text: 'When the WiFi dies mid-game and you stare at the screen like your whole life just flashed before your eyes...', images: ['/images/posts/comedy1.jpg'], likes: 8900, comments: 456, shares: 890, time: '1h', verified: false, type: 'image' as const, vibeTag: 'laughing' },
  { id: 'cp2', user: users[1], text: 'My code works! *changes nothing* My code doesn\'t work... Welcome to programming!', images: [], likes: 12400, comments: 890, shares: 2100, time: '2h', verified: false, type: 'text' as const, vibeTag: 'laughing' },
  { id: 'cp3', user: users[10], text: 'POV: You said "just one more episode" 4 hours ago and now it\'s 3 AM', images: ['/images/posts/late-night-tv.jpg'], likes: 15600, comments: 1200, shares: 3400, time: '3h', verified: false, type: 'image' as const, vibeTag: 'laughing' },
  { id: 'cp4', user: users[2], text: 'That moment when you wave back at someone who wasn\'t waving at you... Then pretend you were fixing your hair', images: [], likes: 23100, comments: 1800, shares: 5600, time: '4h', verified: false, type: 'text' as const, vibeTag: 'laughing' },
  { id: 'cp5', user: users[7], text: 'My browser has 47 tabs open and I need exactly all of them. Do not ask me which ones because I genuinely do not remember opening half of them.', images: [], likes: 9800, comments: 670, shares: 2100, time: '5h', verified: false, type: 'text' as const, vibeTag: 'laughing' },
  { id: 'cp6', user: users[0], text: 'Client: "Make it pop." Me: *adds a drop shadow* Client: "PERFECT!" The design industry is wild sometimes.', images: ['/images/posts/art-block-blank.jpg'], likes: 14200, comments: 980, shares: 3400, time: '6h', verified: true, type: 'image' as const, vibeTag: 'laughing' },
  { id: 'cp7', user: users[10], text: 'Tried to do a kickflip on camera. The camera saw something that was definitely NOT a kickflip. The ground and I are now in a committed relationship.', images: ['/images/posts/basketball.jpg'], likes: 11300, comments: 780, shares: 2900, time: '7h', verified: false, type: 'image' as const, vibeTag: 'laughing' },
  { id: 'cp8', user: users[1], text: 'Debugging is like being the detective in a crime movie where you are also the murderer. The bug was me all along.', images: [], likes: 18700, comments: 1340, shares: 4500, time: '8h', verified: false, type: 'text' as const, vibeTag: 'laughing' },
];

// Hub posts for each hub
export const hubPosts: Record<string, Array<{id: string, userId: string, userName: string, userAvatar: string, text: string, likes: number, comments: number, time: string}>> = {
  h1: [
    { id: 'hp1-1', userId: 'u1', userName: 'Jessica Art', userAvatar: '/images/avatars/bots/bot01.jpg', text: 'Just finished this cyberpunk cityscape! What do you all think? Feedback welcome!', likes: 234, comments: 45, time: '30m' },
    { id: 'hp1-2', userId: 'u7', userName: 'Nova Blaze', userAvatar: '/images/avatars/bots/bot12.jpg', text: 'Anyone else using Procreate for digital art? Looking for brush recommendations!', likes: 89, comments: 23, time: '1h' },
    { id: 'hp1-3', userId: 'u4', userName: 'Marcus Rivera', userAvatar: '/images/avatars/bots/bot04.jpg', text: 'Art block is REAL. Been staring at a blank canvas for 2 hours. Send help and inspiration!', likes: 567, comments: 78, time: '2h' },
  ],
  h2: [
    { id: 'hp2-1', userId: 'u4', userName: 'Marcus Rivera', userAvatar: '/images/avatars/bots/bot04.jpg', text: 'New choreo dropping this weekend! Been working on something special for the ORRA Dance Off!', likes: 456, comments: 89, time: '15m' },
    { id: 'hp2-2', userId: 'u10', userName: 'Luna Sky', userAvatar: '/images/avatars/bots/bot10.jpg', text: 'Anyone want to collab on a duet dance? Looking for a partner for the challenge!', likes: 234, comments: 56, time: '45m' },
  ],
  h3: [
    { id: 'hp3-1', userId: 'u6', userName: 'Tech Daily', userAvatar: '/images/avatars/bots/bot06.jpg', text: 'New AI model just dropped and it is INSANE. The creative applications are endless!', likes: 890, comments: 123, time: '20m' },
    { id: 'hp3-2', userId: 'u2', userName: 'David Chen', userAvatar: '/images/avatars/bots/bot02.jpg', text: 'Just built my first app with the new SDK. Documentation could use some work but the possibilities are amazing!', likes: 345, comments: 67, time: '1h' },
  ],
  h4: [
    { id: 'hp4-1', userId: 'u9', userName: 'Music Central', userAvatar: '/images/avatars/bots/bot09.jpg', text: 'Studio session went crazy last night! New track coming this Friday!', likes: 678, comments: 90, time: '30m' },
    { id: 'hp4-2', userId: 'u12', userName: 'Nova Blaze', userAvatar: '/images/avatars/bots/bot12.jpg', text: 'Beat making tutorial dropping tomorrow! Going to show you my whole workflow', likes: 445, comments: 56, time: '2h' },
  ],
  h5: [
    { id: 'hp5-1', userId: 'u7', userName: 'Wellness Guru', userAvatar: '/images/avatars/bots/bot07.jpg', text: 'Morning routine tip: 5 minutes of breathwork before checking your phone. Game changer!', likes: 567, comments: 78, time: '1h' },
    { id: 'hp5-2', userId: 'u11', userName: 'Kai Storm', userAvatar: '/images/avatars/bots/bot11.jpg', text: 'Just hit a new PR on deadlifts! Consistency is key. Keep pushing!', likes: 345, comments: 45, time: '3h' },
  ],
  h6: [
    { id: 'hp6-1', userId: 'u5', userName: 'Elena Rodriguez', userAvatar: '/images/avatars/bots/bot05.jpg', text: 'Made authentic paella from my abuela\'s recipe! The secret is the saffron!', likes: 789, comments: 134, time: '45m' },
    { id: 'hp6-2', userId: 'u3', userName: 'Sarah Kim', userAvatar: '/images/avatars/bots/bot03.jpg', text: 'Best ramen spot in the city? Need recommendations for this weekend!', likes: 234, comments: 89, time: '2h' },
  ],
};

// Dance challenge recent entries (for entries tab)
export const danceEntries = [
  { id: 'de1', userId: 'u4', userName: 'Marcus Rivera', userAvatar: '/images/avatars/bots/bot04.jpg', thumbnail: '/images/dance/entry0.jpg', likes: 98420, description: 'Electric slide meets hip-hop!' },
  { id: 'de2', userId: 'u10', userName: 'Luna Sky', userAvatar: '/images/avatars/bots/bot10.jpg', thumbnail: '/images/dance/entry1.jpg', likes: 87650, description: 'Contemporary fusion piece' },
  { id: 'de3', userId: 'u1', userName: 'Jessica Art', userAvatar: '/images/avatars/bots/bot01.jpg', thumbnail: '/images/dance/entry2.jpg', likes: 76340, description: 'Voguing with a twist' },
  { id: 'de4', userId: 'u12', userName: 'Nova Blaze', userAvatar: '/images/avatars/bots/bot12.jpg', thumbnail: '/images/dance/entry3.jpg', likes: 65230, description: 'Breakdance meets ballet' },
  { id: 'de5', userId: 'u5', userName: 'Elena Rodriguez', userAvatar: '/images/avatars/bots/bot05.jpg', thumbnail: '/images/dance/entry4.jpg', likes: 54120, description: 'Latin dance fusion' },
  { id: 'de6', userId: 'u11', userName: 'Kai Storm', userAvatar: '/images/avatars/bots/bot11.jpg', thumbnail: '/images/dance/entry5.jpg', likes: 43010, description: 'Krump energy!' },
  { id: 'de7', userId: 'u2', userName: 'David Chen', userAvatar: '/images/avatars/bots/bot02.jpg', thumbnail: '/images/dance/entry6.jpg', likes: 38900, description: 'Robot dance challenge' },
  { id: 'de8', userId: 'u8', userName: 'Cyber Drifter', userAvatar: '/images/avatars/bots/bot08.jpg', thumbnail: '/images/dance/entry7.jpg', likes: 32780, description: 'Cyberpunk choreography' },
];

// Auto-reply messages for chat (contextual)
export const chatAutoReplies: Record<string, string[]> = {
  u1: ['Your art is incredible!', 'Let\'s collab on something!', 'Have you seen the new challenge?', 'OMG I love that idea!', 'Send me the link!'],
  u2: ['Check out my new track!', 'Studio session was fire today', 'Let\'s jam this weekend?', 'That beat is sick!', 'Working on something special'],
  u3: ['That photo is stunning!', 'We should shoot together!', 'Golden hour is the best hour', 'What camera do you use?', 'Editing tips?'],
  u4: ['Let\'s go! Challenge time!', 'New choreo is ready', 'Practice makes perfect', 'Dance battle soon?', 'That routine was insane!'],
  u5: ['Barcelona is amazing!', 'Travel goals for real', 'The food here is incredible', 'Missing home a bit', 'Adventure awaits!'],
  u6: ['Tech news just broke!', 'AI is evolving so fast', 'This startup is disrupting everything', 'Innovation never sleeps', 'The future is now'],
  u7: ['Breathe in, breathe out', 'Morning meditation was powerful', 'Wellness tip: hydrate!', 'Your energy is everything', 'Mindfulness matters'],
  u8: ['The cyber world is wild', 'Hacking the system', 'Digital nomad life', 'Code never lies', 'Cyberpunk vibes today'],
  u9: ['New single dropping!', 'The beat goes hard', 'Studio vibes only', 'Music is life', 'Let\'s make a hit'],
  u10: ['Ready for the challenge?', 'Dance practice was intense', 'Let\'s create something epic', 'Your moves are fire!', 'Collab?'],
  u11: ['Skate sesh was lit', 'New trick landed!', 'The park is calling', 'Board maintenance time', 'Skate and create'],
  u12: ['Beat making all night', 'New sound discovered', 'Production level up', 'The drop is coming', 'Remix potential!'],
};

export const reels = [
  { id: 'r1', title: 'Neon Dance Routine', creator: users[3], views: '2.4M', viewsNum: 2400000, thumbnail: '/images/reels/reel1.jpg', likes: 189000, comments: 12400, isRemix: true, category: 'Dance', song: 'Neon Dreams - DJ Prism ft. Luna' },
  { id: 'r2', title: 'Cooking Hacks: 5min Meals', creator: users[4], views: '890K', viewsNum: 890000, thumbnail: '/images/reels/reel2.jpg', likes: 67000, comments: 5600, category: 'Food', song: 'Lo-Fi Kitchen Beats' },
  { id: 'r3', title: 'Epic Guitar Solo', creator: users[8], views: '1.2M', viewsNum: 1200000, thumbnail: '/images/reels/reel3.jpg', likes: 145000, comments: 8900, category: 'Music', song: 'Shredding Neon - Music Central' },
  { id: 'r4', title: 'Morning Yoga Flow', creator: users[6], views: '567K', viewsNum: 567000, thumbnail: '/images/reels/reel4.jpg', likes: 34000, comments: 2300, isLive: true, category: 'Sports', song: 'Zen Flow - Wellness Sounds' },
  { id: 'r5', title: 'Street Art Process', creator: users[0], views: '1.8M', viewsNum: 1800000, thumbnail: '/images/reels/reel5.jpg', likes: 210000, comments: 15600, isRemix: true, category: 'Art', song: 'Canvas Dreams - Art Beats' },
  { id: 'r6', title: 'Comedy: When WiFi Dies', creator: users[7], views: '3.1M', viewsNum: 3100000, thumbnail: '/images/reels/reel6.jpg', likes: 445000, comments: 34200, category: 'Comedy', song: 'Fail Sound Effect' },
  { id: 'r7', title: 'Skateboard Tricks', creator: users[10], views: '920K', viewsNum: 920000, thumbnail: '/images/reels/reel7.jpg', likes: 78000, comments: 4500, category: 'Sports', song: 'Skate Punk Anthems' },
  { id: 'r8', title: 'Beat Making Tutorial', creator: users[11], views: '1.5M', viewsNum: 1500000, thumbnail: '/images/reels/reel8.jpg', likes: 167000, comments: 11200, isRemix: true, category: 'Music', song: 'Beat Lab - Nova Blaze' },
  { id: 'r9', title: 'Fashion Haul: Summer', creator: users[9], views: '670K', viewsNum: 670000, thumbnail: '/images/reels/reel9.jpg', likes: 45000, comments: 3200, isLive: true, category: 'Trending', song: 'Runway Vibes - Luna Sky' },
  { id: 'r10', title: 'Dance Battle Finals', creator: users[3], views: '4.2M', viewsNum: 4200000, thumbnail: '/images/reels/reel10.jpg', likes: 567000, comments: 45600, isRemix: true, category: 'Dance', song: 'Battle Cry - DJ Prism' },
  { id: 'r11', title: 'Sunset Timelapse', creator: users[4], views: '1.1M', viewsNum: 1100000, thumbnail: '/images/reels/reel11.jpg', likes: 98000, comments: 6700, category: 'Trending', song: 'Golden Hour - Ambient Mix' },
  { id: 'r12', title: 'Piano Cover: Neon Dreams', creator: users[8], views: '780K', viewsNum: 780000, thumbnail: '/images/reels/reel12.jpg', likes: 56000, comments: 4100, category: 'Music', song: 'Neon Dreams (Piano Version)' },
];

export const danceChallenge = {
  id: 'dc1',
  name: 'ORRA DANCE OFF 2027',
  hashtag: '#OrraDanceOff2027',
  song: 'Neon Dreams - DJ Prism ft. Luna',
  entries: 45230,
  timeRemaining: 72 * 60 * 60,
  bannerImage: '/api/uploads?path=images/dance-banner.png',
  description: 'Show us your best moves! Create a dance video using the official track and tag #OrraDanceOff2027. The top 3 entries with the most likes win exclusive ORRA plaques and tokens!',
  prize: '100,000 ORRA + Champion Plaque',
  secondPrize: '50,000 ORRA + Runner-Up Plaque',
  thirdPrize: '25,000 ORRA + 3rd Place Plaque',
};

export const leaderboard = [
  { id: 'l1', user: users[3], likes: 98420, handle: '@marcusr', change: 'up' as const },
  { id: 'l2', user: users[9], likes: 87650, handle: '@lunasky', change: 'up' as const },
  { id: 'l3', user: users[0], likes: 76340, handle: '@jessart', change: 'same' as const },
  { id: 'l4', user: users[11], likes: 65230, handle: '@novablaze', change: 'down' as const },
  { id: 'l5', user: users[4], likes: 54120, handle: '@elenarod', change: 'up' as const },
  { id: 'l6', user: users[10], likes: 43010, handle: '@kaistorm', change: 'down' as const },
  { id: 'l7', user: users[1], likes: 38900, handle: '@davchen', change: 'same' as const },
  { id: 'l8', user: users[7], likes: 32780, handle: '@cyberdrift', change: 'up' as const },
  { id: 'l9', user: users[2], likes: 28650, handle: '@sarahkim', change: 'down' as const },
  { id: 'l10', user: users[8], likes: 24530, handle: '@musiccentral', change: 'same' as const },
  { id: 'l11', user: users[6], likes: 20340, handle: '@wellnessg', change: 'up' as const },
  { id: 'l12', user: users[5], likes: 18200, handle: '@techdaily', change: 'down' as const },
];

export const pastChallenges = [
  { name: '#NeonNights', winner: users[3], likes: 112000, date: 'Jan 2027', entries: 34200 },
  { name: '#BeatDrop', winner: users[0], likes: 95000, date: 'Dec 2026', entries: 28100 },
  { name: '#GrooveCity', winner: users[9], likes: 88000, date: 'Nov 2026', entries: 25600 },
];

export const trending = [
  { tag: '#OrraDanceOff2027', posts: '45K posts', category: 'Dance' },
  { tag: '#CyberPunk2077', posts: '124K posts', category: 'Gaming' },
  { tag: '#AIart', posts: '234K posts', category: 'Tech' },
  { tag: '#MinimalistSetup', posts: '89K posts', category: 'Lifestyle' },
  { tag: '#SustainableLiving', posts: '67K posts', category: 'Lifestyle' },
];

export const hubs = [
  { id: 'h1', name: 'Digital Artists', members: 12400, online: 342, icon: '🎨', cover: '/images/hub1.jpg', description: 'Share your digital creations' },
  { id: 'h2', name: 'Dance Crew', members: 8900, online: 567, icon: '💃', cover: '/images/hub2.jpg', description: 'All dance styles welcome' },
  { id: 'h3', name: 'Tech Innovators', members: 15600, online: 890, icon: '🚀', cover: '/images/hub3.jpg', description: 'The future starts here' },
  { id: 'h4', name: 'Music Makers', members: 9200, online: 234, icon: '🎵', cover: '/images/hub4.jpg', description: 'Create and collaborate' },
  { id: 'h5', name: 'Fitness First', members: 11000, online: 456, icon: '💪', cover: '/images/hub5.jpg', description: 'Level up your fitness' },
  { id: 'h6', name: 'Foodies Unite', members: 7800, online: 123, icon: '🍜', cover: '/images/hub6.jpg', description: 'Food from around the world' },
];

export const suggestedHubs = [
  { id: 'h7', name: 'Photography Club', icon: '📷', members: 5600, desc: 'Share your best shots' },
  { id: 'h8', name: 'Gaming Arena', icon: '🎮', members: 8900, desc: 'Compete and connect' },
  { id: 'h9', name: 'Book Lovers', icon: '📚', members: 3200, desc: 'Read and discuss' },
  { id: 'h10', name: 'Travel Nomads', icon: '✈️', members: 4100, desc: 'Explore the world together' },
];

export const messages = [
  { id: 'm1', user: users[0], lastMessage: 'OMG that dance was insane! We need to collab!', time: '2m', unread: 2 },
  { id: 'm2', user: users[1], lastMessage: 'Check out this new track I made', time: '15m', unread: 0 },
  { id: 'm3', user: users[3], lastMessage: 'You ready for the challenge? Let us go!', time: '1h', unread: 1 },
  { id: 'm4', user: users[4], lastMessage: 'Barcelona photos are up! Check them', time: '2h', unread: 0 },
  { id: 'm5', user: users[6], lastMessage: 'Namaste! Morning session tomorrow?', time: '3h', unread: 0 },
  { id: 'm6', user: users[8], lastMessage: 'Listen to the new single! Just dropped!', time: '5h', unread: 3 },
  { id: 'm7', user: users[9], lastMessage: 'Let us collab on the next reel', time: '6h', unread: 0 },
  { id: 'm8', user: users[10], lastMessage: 'Skate session tomorrow at the park?', time: '1d', unread: 0 },
  { id: 'm9', user: users[11], lastMessage: 'New beat just dropped, need your feedback', time: '2d', unread: 0 },
];

// Initial chat history for each conversation
export const initialChatHistory: Record<string, { senderId: string; text: string }[]> = {
  m1: [
    { senderId: 'u1', text: 'Hey! Did you see the new dance challenge?' },
    { senderId: 'u13', text: 'Yes!! The moves are incredible this year' },
    { senderId: 'u1', text: 'OMG that dance was insane! We need to collab!' },
  ],
  m2: [
    { senderId: 'u2', text: 'Working on something cool in the studio' },
    { senderId: 'u13', text: 'Can not wait to hear it!' },
    { senderId: 'u2', text: 'Check out this new track I made' },
  ],
  m3: [
    { senderId: 'u4', text: 'The dance off is about to start!' },
    { senderId: 'u13', text: 'I am so ready for this' },
    { senderId: 'u4', text: 'You ready for the challenge? Let us go!' },
  ],
  m4: [
    { senderId: 'u5', text: 'Barcelona is absolutely stunning' },
    { senderId: 'u13', text: 'Show me the photos!' },
    { senderId: 'u5', text: 'Barcelona photos are up! Check them' },
  ],
  m5: [
    { senderId: 'u7', text: 'Morning meditation was amazing today' },
    { senderId: 'u13', text: 'I need to get back into that routine' },
    { senderId: 'u7', text: 'Namaste! Morning session tomorrow?' },
  ],
  m6: [
    { senderId: 'u9', text: 'Studio session went crazy last night' },
    { senderId: 'u13', text: 'When is it dropping?' },
    { senderId: 'u9', text: 'Listen to the new single! Just dropped!' },
  ],
  m7: [
    { senderId: 'u10', text: 'That reel we talked about?' },
    { senderId: 'u13', text: 'Still editing, almost done!' },
    { senderId: 'u10', text: 'Let us collab on the next reel' },
  ],
  m8: [
    { senderId: 'u11', text: 'The weather is perfect for skating' },
    { senderId: 'u13', text: 'Let me grab my board!' },
    { senderId: 'u11', text: 'Skate session tomorrow at the park?' },
  ],
  m9: [
    { senderId: 'u12', text: 'Just finished a new beat' },
    { senderId: 'u13', text: 'Send it over!' },
    { senderId: 'u12', text: 'New beat just dropped, need your feedback' },
  ],
};

export const notifications = [
  { id: 'n1', user: users[0], action: 'liked your dance video', time: '2m', thumbnail: '/images/avatars/bots/bot01.jpg', type: 'like' as const },
  { id: 'n2', user: users[1], action: 'started following you', time: '15m', thumbnail: null, type: 'follow' as const },
  { id: 'n3', user: users[3], action: 'commented: "Insane moves!"', time: '30m', thumbnail: '/images/avatars/bots/bot03.jpg', type: 'comment' as const },
  { id: 'n4', user: users[4], action: 'shared your post to their ORRA', time: '1h', thumbnail: '/images/avatars/bots/bot04.jpg', type: 'share' as const },
  { id: 'n5', user: users[6], action: 'mentioned you in a comment', time: '2h', thumbnail: null, type: 'mention' as const },
  { id: 'n6', user: users[8], action: 'started following you', time: '3h', thumbnail: null, type: 'follow' as const },
  { id: 'n7', user: users[7], action: 'liked your dance challenge entry', time: '4h', thumbnail: '/images/avatars/bots/bot07.jpg', type: 'like' as const },
  { id: 'n8', user: users[9], action: 'remixed your reel', time: '5h', thumbnail: '/images/avatars/bots/bot08.jpg', type: 'remix' as const },
  { id: 'n9', user: users[10], action: 'started following you', time: '6h', thumbnail: null, type: 'follow' as const },
  { id: 'n10', user: users[11], action: 'liked your comment', time: '8h', thumbnail: null, type: 'like' as const },
  { id: 'n11', user: users[5], action: 'featured your post in Tech Daily', time: '12h', thumbnail: '/images/avatars/bots/bot11.jpg', type: 'feature' as const },
];

export const exploreCategories = ['Trending', 'Music', 'Art', 'Tech', 'Sports', 'Food', 'Fashion', 'Dance'];

export const exploreItems = [
  { id: 'e1', image: '/images/posts/art1.jpg', title: 'Cyberpunk Cityscape', likes: '12.3K', creator: users[7], category: 'Art' },
  { id: 'e2', image: '/images/posts/barcelona-sunset.jpg', title: 'Sunset Vibes', likes: '8.7K', creator: users[4], category: 'Trending' },
  { id: 'e3', image: '/images/posts/dance1.jpg', title: 'Street Dance Battle', likes: '45.2K', creator: users[3], category: 'Dance' },
  { id: 'e4', image: '/images/posts/butter-chicken.jpg', title: 'Neon Art Gallery', likes: '23.1K', creator: users[0], category: 'Art' },
  { id: 'e5', image: '/images/posts/studio-beats.jpg', title: 'Tech Setup Goals', likes: '6.4K', creator: users[5], category: 'Tech' },
  { id: 'e6', image: '/images/posts/studio-beats.jpg', title: 'Dance Practice', likes: '34.8K', creator: users[9], category: 'Dance' },
  { id: 'e7', image: '/images/posts/studio-beats.jpg', title: 'Fitness Journey', likes: '9.2K', creator: users[6], category: 'Sports' },
  { id: 'e8', image: '/images/posts/studio-beats.jpg', title: 'Music Production', likes: '15.6K', creator: users[11], category: 'Music' },
  { id: 'e9', image: '/images/posts/studio-beats.jpg', title: 'Fashion Forward', likes: '7.8K', creator: users[9], category: 'Fashion' },
  { id: 'e10', image: '/images/posts/studio-beats.jpg', title: 'Digital Nomad Life', likes: '19.3K', creator: users[4], category: 'Trending' },
  { id: 'e11', image: '/images/posts/studio-beats.jpg', title: 'Neon Dreams Cover', likes: '56.1K', creator: users[8], category: 'Music' },
  { id: 'e12', image: '/images/posts/studio-beats.jpg', title: 'Gaming Setup', likes: '11.4K', creator: users[7], category: 'Tech' },
];

// Vibe tag labels for display
export const vibeLabels: Record<string, string> = {
  hyped: 'Hyped / Energetic',
  laughing: 'Laughing / Comedy',
  chill: 'Chill / Relaxed',
  dramatic: 'Extra / Dramatic',
  focused: 'Focused / Learning',
  peaceful: 'Peaceful / Calm',
  news: 'News / Politics',
  sports: 'Sports / Athletics',
};

// Vibe post counts
export const vibePostCounts: Record<string, number> = {
  hyped: 9,
  laughing: 6,
  chill: 6,
  dramatic: 5,
  focused: 6,
  peaceful: 4,
};

// Vibe friends (which friends are in each vibe)
export const vibeFriends: Record<string, string[]> = {
  hyped: ['Marcus Rivera', 'Luna Sky', 'Music Central'],
  laughing: ['Cyber Drifter', 'David Chen'],
  chill: ['Elena Rodriguez'],
  dramatic: ['Jessica Art'],
  focused: ['Tech Daily'],
  peaceful: ['Wellness Guru'],
};
